### ISSUE TITLE
Using Optax to find output_scale

### ISSUE THREAD

**Issue by lahramon** [pnkraemer/probdiffeq#668]
Hi, 

I am trying to use the Fenrir likelihood to estimate the output scale of the ODE solver based on the [Optax parameter estimation example](https://pnkraemer.github.io/probdiffeq/examples_parameter_estimation/physics_enhanced_regression_1/) you provided (thanks!). 
I noticed that when trying to include the output_scale as a parameter, the sensitivities of the likelihood with respect to it are always "nan". [Here](https://github.com/pnkraemer/probdiffeq/files/13069861/test_probnumdiff_likelihood.zip) you find the modified Optax example reproducing the issue. Also, I noticed that the output scale does not seem to influence the solution estimate computed by the ODE solver; however, the output-scale I set is still returned as part of the solution (the solver is already the non-adaptive uniform grid-based ODE solver right?).

Do you think it would be possible to compute sensitivities with respect to the output scale?

Thanks!

**Comment by pnkraemer** [comment]
Hi!

Thanks for creating the issue. In general, everything you're asking for sounds absolutely reasonable, and tracking down what goes wrong on the probdiffeq-side of things will be useful.
  
A quick reply before I find the time to look into things in more detail: 

> I noticed that when trying to include the output_scale as a parameter, the sensitivities of the likelihood with respect to it are always "nan

Does this depend on the solver/step-sizes/general config? And what do you get with `jax.debug_nans` (https://jax.readthedocs.io/en/latest/debugging/flags.html)?

> Also, I noticed that the output scale does not seem to influence the solution estimate computed by the ODE solver

The mean (and the derived solution-estimate) should not be affected unless you choose dynamic calibration. The covariance should.  Could you please double check this is true? Thanks!

What do you think? :)

**Comment by lahramon** [comment]
Hey!

Thanks for the super quick reply :D

> Does this depend on the solver/step-sizes/general config? And what do you get with jax.debug_nans (https://jax.readthedocs.io/en/latest/debugging/flags.html)?

I just checked different ODEs (lotka_volterra, affine_independent, logistic) and step sizes (up to just 2-3 very small steps),  with the Nan-Flag activated as you suggested; I always get the following error message: 

`FloatingPointError: invalid value (nan) encountered in jit(scan)`

(see [updated script](https://github.com/pnkraemer/probdiffeq/files/13070910/test_probnumdiff_likelihood_updt.zip)).

> The mean (and the derived solution-estimate) should not be affected unless you choose dynamic calibration. The covariance should. Could you please double check this is true? Thanks!

Ah true; my bad sorry. It does scale the covariances as expected while keeping the mean the same.

Thanks a lot for looking into this!

**Comment by lahramon** [comment]
Hi,
thanks a lot for the quick feedback and fix: this helps a lot indeed! 
I am not very experienced with Jax, so I also must admit that I have no idea why this works and the previous version did not. Again, thanks a bunch!

**Comment by pnkraemer** [comment]
Good to hear! :tada: 

I am also not entirely sure why things changed, but I assume it is due to fewer global variables, which may imply fewer side effects.

Is there anything we could've done on the probdiffeq-documentation side that would've helped you? For example, there is a "troubleshooting" section on the website (https://pnkraemer.github.io/probdiffeq/getting_started/troubleshooting/) where we can add some information if you think that makes sense.

**Comment by lahramon** [comment]
Hmm this seems more like a jax-autodiff related issue right? As far as I read the Jax documentation so far, debugging nans is generally quite challenging. Maybe adding this as another example might help? 
But generally it is a bit hard to say how to help other people with similar issues since we did not exactly figure out yet what the problem was :thinking:

**Comment by pnkraemer** [comment]
I dug a little bit deeper -- exchanging the order of `output_scale` and `ode_params` in the solve() function in the snippet I posted above makes it crash with NaNs as well. Conversely, splitting output_scale and ode-parameters in your example into two arguments (instead of the array of stacked arguments) preserves NaNs, but reversing their order fixes the code.

Weird. That is certainly unexpected.

This seems to be an issue with JAX; however, I have not yet managed to create a minimal example that reproduces the problem without involving probdiffeq (in which case this issue could be passed on to the jax repo).

**Comment by pnkraemer** [comment]
My last comment is incorrect.

I realise that the code snippet I posted above does not do what you intended. It only computes the gradient with respect to the ODE parameters. The gradient with respect to the output scale is NaN.

(My error was that value_and_grad computes the gradient with respect to the zeroth argument unless specified otherwise. This explains why the order matters.)

Altogether, let's reopen this issue because something seems off regarding the gradient with respect to the output scale. I will have a closer look into this soon.

**Comment by lahramon** [comment]
Thanks a lot for looking into this!

**Comment by pnkraemer** [comment]
#669 should fix this (that was quite a subtle issue, to be honest). 

Could you update your probdiffeq version to 0.3.1 and let me know whether everything works now? Let's make sure everything runs smoothly now!

**Comment by lahramon** [comment]
Yes, it seems to work! Thanks a lot for the incredibly quick fix!

**Comment by pnkraemer** [comment]
Fantastic. Let me know if you run into more issues!
